### ISSUE TITLE
Merge two files in simulation-study

### ISSUE THREAD

**Issue by drisso** [stephaniehicks/benchmark-hdf5-clustering#1]
Keeping the most current version of accuracy and time comparison. Remove mem profiling.

**Comment by drisso** [comment]
@ruoxi430

**Comment by epurdom** [comment]
library(benchmarkme) #to get information about RAM and CPUs on machine:
print(get_ram())
print(get_cpu())
print(sessionInfo())

**Comment by drisso** [comment]
print(BiocManager::version())

**Comment by YuweiNi45** [comment]
- Keep 'simulate_hdf5_accuracy' RMD file which contains the accuracy and time comparison.  
- Add the information part at the end of RMD file
